package jpize.opengl.gl;

import java.nio.*;

public interface GL15I extends GL14I {

    int GL_FOG_COORD_SRC = 33872;
    int GL_FOG_COORD = 33873;
    int GL_CURRENT_FOG_COORD = 33875;
    int GL_FOG_COORD_ARRAY_TYPE = 33876;
    int GL_FOG_COORD_ARRAY_STRIDE = 33877;
    int GL_FOG_COORD_ARRAY_POINTER = 33878;
    int GL_FOG_COORD_ARRAY = 33879;
    int GL_FOG_COORD_ARRAY_BUFFER_BINDING = 34973;
    int GL_SRC0_RGB = 34176;
    int GL_SRC1_RGB = 34177;
    int GL_SRC2_RGB = 34178;
    int GL_SRC0_ALPHA = 34184;
    int GL_SRC1_ALPHA = 34185;
    int GL_SRC2_ALPHA = 34186;
    int GL_ARRAY_BUFFER = 34962;
    int GL_ELEMENT_ARRAY_BUFFER = 34963;
    int GL_ARRAY_BUFFER_BINDING = 34964;
    int GL_ELEMENT_ARRAY_BUFFER_BINDING = 34965;
    int GL_VERTEX_ARRAY_BUFFER_BINDING = 34966;
    int GL_NORMAL_ARRAY_BUFFER_BINDING = 34967;
    int GL_COLOR_ARRAY_BUFFER_BINDING = 34968;
    int GL_INDEX_ARRAY_BUFFER_BINDING = 34969;
    int GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING = 34970;
    int GL_EDGE_FLAG_ARRAY_BUFFER_BINDING = 34971;
    int GL_SECONDARY_COLOR_ARRAY_BUFFER_BINDING = 34972;
    int GL_FOG_COORDINATE_ARRAY_BUFFER_BINDING = 34973;
    int GL_WEIGHT_ARRAY_BUFFER_BINDING = 34974;
    int GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = 34975;
    int GL_STREAM_DRAW = 35040;
    int GL_STREAM_READ = 35041;
    int GL_STREAM_COPY = 35042;
    int GL_STATIC_DRAW = 35044;
    int GL_STATIC_READ = 35045;
    int GL_STATIC_COPY = 35046;
    int GL_DYNAMIC_DRAW = 35048;
    int GL_DYNAMIC_READ = 35049;
    int GL_DYNAMIC_COPY = 35050;
    int GL_READ_ONLY = 35000;
    int GL_WRITE_ONLY = 35001;
    int GL_READ_WRITE = 35002;
    int GL_BUFFER_SIZE = 34660;
    int GL_BUFFER_USAGE = 34661;
    int GL_BUFFER_ACCESS = 35003;
    int GL_BUFFER_MAPPED = 35004;
    int GL_BUFFER_MAP_POINTER = 35005;
    int GL_SAMPLES_PASSED = 35092;
    int GL_QUERY_COUNTER_BITS = 34916;
    int GL_CURRENT_QUERY = 34917;
    int GL_QUERY_RESULT = 34918;
    int GL_QUERY_RESULT_AVAILABLE = 34919;

    void glBindBuffer(int target, int buffer);
    void glDeleteBuffers(IntBuffer buffers);
    void glDeleteBuffers(int buffer);
    void glGenBuffers(IntBuffer buffers);
    int glGenBuffers();
    boolean glIsBuffer(int buffer);
    void glBufferData(int target, long size, int usage);
    void glBufferData(int target, ByteBuffer data, int usage);
    void glBufferData(int target, ShortBuffer data, int usage);
    void glBufferData(int target, IntBuffer data, int usage);
    void glBufferData(int target, LongBuffer data, int usage);
    void glBufferData(int target, FloatBuffer data, int usage);
    void glBufferData(int target, DoubleBuffer data, int usage);
    void glBufferSubData(int target, long offset, ByteBuffer data);
    void glBufferSubData(int target, long offset, ShortBuffer data);
    void glBufferSubData(int target, long offset, IntBuffer data);
    void glBufferSubData(int target, long offset, LongBuffer data);
    void glBufferSubData(int target, long offset, FloatBuffer data);
    void glBufferSubData(int target, long offset, DoubleBuffer data);
    void glGetBufferSubData(int target, long offset, ByteBuffer data);
    void glGetBufferSubData(int target, long offset, ShortBuffer data);
    void glGetBufferSubData(int target, long offset, IntBuffer data);
    void glGetBufferSubData(int target, long offset, LongBuffer data);
    void glGetBufferSubData(int target, long offset, FloatBuffer data);
    void glGetBufferSubData(int target, long offset, DoubleBuffer data);
    ByteBuffer glMapBuffer(int target, int access);
    ByteBuffer glMapBuffer(int target, int access, ByteBuffer old_buffer);
    ByteBuffer glMapBuffer(int target, int access, long length, ByteBuffer old_buffer);
    boolean glUnmapBuffer(int target);
    void glGetBufferParameteriv(int target, int pname, IntBuffer params);
    int glGetBufferParameteri(int target, int pname);
    // void glGetBufferPointerv(int target, int pname, PointerBuffer params);
    long glGetBufferPointer(int target, int pname);
    void glGenQueries(IntBuffer ids);
    int glGenQueries();
    void glDeleteQueries(IntBuffer ids);
    void glDeleteQueries(int id);
    boolean glIsQuery(int id);
    void glBeginQuery(int target, int id);
    void glEndQuery(int target);
    void glGetQueryiv(int target, int pname, IntBuffer params);
    int glGetQueryi(int target, int pname);
    void glGetQueryObjectiv(int id, int pname, IntBuffer params);
    void glGetQueryObjectiv(int id, int pname, long params);
    int glGetQueryObjecti(int id, int pname);
    void glGetQueryObjectuiv(int id, int pname, IntBuffer params);
    void glGetQueryObjectuiv(int id, int pname, long params);
    int glGetQueryObjectui(int id, int pname);
    void glDeleteBuffers(int[] buffers);
    void glGenBuffers(int[] buffers);
    void glBufferData(int target, short[] data, int usage);
    void glBufferData(int target, int[] data, int usage);
    void glBufferData(int target, long[] data, int usage);
    void glBufferData(int target, float[] data, int usage);
    void glBufferData(int target, double[] data, int usage);
    void glBufferSubData(int target, long offset, short[] data);
    void glBufferSubData(int target, long offset, int[] data);
    void glBufferSubData(int target, long offset, long[] data);
    void glBufferSubData(int target, long offset, float[] data);
    void glBufferSubData(int target, long offset, double[] data);
    void glGetBufferSubData(int target, long offset, short[] data);
    void glGetBufferSubData(int target, long offset, int[] data);
    void glGetBufferSubData(int target, long offset, long[] data);
    void glGetBufferSubData(int target, long offset, float[] data);
    void glGetBufferSubData(int target, long offset, double[] data);
    void glGetBufferParameteriv(int target, int pname, int[] params);
    void glGenQueries(int[] ids);
    void glDeleteQueries(int[] ids);
    void glGetQueryiv(int target, int pname, int[] params);
    void glGetQueryObjectiv(int id, int pname, int[] params);
    void glGetQueryObjectuiv(int id, int pname, int[] params);
    
}
