package jpize.opengl.gl;

import java.nio.*;

public interface GLI32 extends GLI31 {

    int GL_CONTEXT_PROFILE_MASK = 37158;
    int GL_CONTEXT_CORE_PROFILE_BIT = 1;
    int GL_CONTEXT_COMPATIBILITY_PROFILE_BIT = 2;
    int GL_MAX_VERTEX_OUTPUT_COMPONENTS = 37154;
    int GL_MAX_GEOMETRY_INPUT_COMPONENTS = 37155;
    int GL_MAX_GEOMETRY_OUTPUT_COMPONENTS = 37156;
    int GL_MAX_FRAGMENT_INPUT_COMPONENTS = 37157;
    int GL_FIRST_VERTEX_CONVENTION = 36429;
    int GL_LAST_VERTEX_CONVENTION = 36430;
    int GL_PROVOKING_VERTEX = 36431;
    int GL_QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION = 36428;
    int GL_TEXTURE_CUBE_MAP_SEAMLESS = 34895;
    int GL_SAMPLE_POSITION = 36432;
    int GL_SAMPLE_MASK = 36433;
    int GL_SAMPLE_MASK_VALUE = 36434;
    int GL_TEXTURE_2D_MULTISAMPLE = 37120;
    int GL_PROXY_TEXTURE_2D_MULTISAMPLE = 37121;
    int GL_TEXTURE_2D_MULTISAMPLE_ARRAY = 37122;
    int GL_PROXY_TEXTURE_2D_MULTISAMPLE_ARRAY = 37123;
    int GL_MAX_SAMPLE_MASK_WORDS = 36441;
    int GL_MAX_COLOR_TEXTURE_SAMPLES = 37134;
    int GL_MAX_DEPTH_TEXTURE_SAMPLES = 37135;
    int GL_MAX_INTEGER_SAMPLES = 37136;
    int GL_TEXTURE_BINDING_2D_MULTISAMPLE = 37124;
    int GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY = 37125;
    int GL_TEXTURE_SAMPLES = 37126;
    int GL_TEXTURE_FIXED_SAMPLE_LOCATIONS = 37127;
    int GL_SAMPLER_2D_MULTISAMPLE = 37128;
    int GL_INT_SAMPLER_2D_MULTISAMPLE = 37129;
    int GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE = 37130;
    int GL_SAMPLER_2D_MULTISAMPLE_ARRAY = 37131;
    int GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY = 37132;
    int GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY = 37133;
    int GL_DEPTH_CLAMP = 34383;
    int GL_GEOMETRY_SHADER = 36313;
    int GL_GEOMETRY_VERTICES_OUT = 36314;
    int GL_GEOMETRY_INPUT_TYPE = 36315;
    int GL_GEOMETRY_OUTPUT_TYPE = 36316;
    int GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS = 35881;
    int GL_MAX_GEOMETRY_UNIFORM_COMPONENTS = 36319;
    int GL_MAX_GEOMETRY_OUTPUT_VERTICES = 36320;
    int GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS = 36321;
    int GL_LINES_ADJACENCY = 10;
    int GL_LINE_STRIP_ADJACENCY = 11;
    int GL_TRIANGLES_ADJACENCY = 12;
    int GL_TRIANGLE_STRIP_ADJACENCY = 13;
    int GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS = 36264;
    int GL_FRAMEBUFFER_ATTACHMENT_LAYERED = 36263;
    int GL_PROGRAM_POINT_SIZE = 34370;
    int GL_MAX_SERVER_WAIT_TIMEOUT = 37137;
    int GL_OBJECT_TYPE = 37138;
    int GL_SYNC_CONDITION = 37139;
    int GL_SYNC_STATUS = 37140;
    int GL_SYNC_FLAGS = 37141;
    int GL_SYNC_FENCE = 37142;
    int GL_SYNC_GPU_COMMANDS_COMPLETE = 37143;
    int GL_UNSIGNALED = 37144;
    int GL_SIGNALED = 37145;
    int GL_SYNC_FLUSH_COMMANDS_BIT = 1;
    long GL_TIMEOUT_IGNORED = -1L;
    int GL_ALREADY_SIGNALED = 37146;
    int GL_TIMEOUT_EXPIRED = 37147;
    int GL_CONDITION_SATISFIED = 37148;
    int GL_WAIT_FAILED = 37149;

    void glGetBufferParameteri64v(int target, int pname, LongBuffer params);
    long glGetBufferParameteri64(int target, int pname);
    void glDrawElementsBaseVertex(int mode, int count, int type, long indices, int basevertex);
    void glDrawElementsBaseVertex(int mode, int type, ByteBuffer indices, int basevertex);
    void glDrawElementsBaseVertex(int mode, ByteBuffer indices, int basevertex);
    void glDrawElementsBaseVertex(int mode, ShortBuffer indices, int basevertex);
    void glDrawElementsBaseVertex(int mode, IntBuffer indices, int basevertex);
    void glDrawRangeElementsBaseVertex(int mode, int start, int end, int count, int type, long indices, int basevertex);
    void glDrawRangeElementsBaseVertex(int mode, int start, int end, int type, ByteBuffer indices, int basevertex);
    void glDrawRangeElementsBaseVertex(int mode, int start, int end, ByteBuffer indices, int basevertex);
    void glDrawRangeElementsBaseVertex(int mode, int start, int end, ShortBuffer indices, int basevertex);
    void glDrawRangeElementsBaseVertex(int mode, int start, int end, IntBuffer indices, int basevertex);
    void glDrawElementsInstancedBaseVertex(int mode, int count, int type, long indices, int primcount, int basevertex);
    void glDrawElementsInstancedBaseVertex(int mode, int type, ByteBuffer indices, int primcount, int basevertex);
    void glDrawElementsInstancedBaseVertex(int mode, ByteBuffer indices, int primcount, int basevertex);
    void glDrawElementsInstancedBaseVertex(int mode, ShortBuffer indices, int primcount, int basevertex);
    void glDrawElementsInstancedBaseVertex(int mode, IntBuffer indices, int primcount, int basevertex);
    // void glMultiDrawElementsBaseVertex(int mode, IntBuffer count, int type, PointerBuffer indices, IntBuffer basevertex);
    void glProvokingVertex(int mode);
    void glTexImage2DMultisample(int target, int samples, int internalformat, int width, int height, boolean fixedsamplelocations);
    void glTexImage3DMultisample(int target, int samples, int internalformat, int width, int height, int depth, boolean fixedsamplelocations);
    void glGetMultisamplefv(int pname, int index, FloatBuffer val);
    float glGetMultisamplef(int pname, int index);
    void glSampleMaski(int index, int mask);
    void glFramebufferTexture(int target, int attachment, int texture, int level);
    long glFenceSync(int condition, int flags);
    boolean glIsSync(long sync);
    void glDeleteSync(long sync);
    int glClientWaitSync(long sync, int flags, long timeout);
    void glWaitSync(long sync, int flags, long timeout);
    void glGetInteger64v(int pname, LongBuffer params);
    long glGetInteger64(int pname);
    void glGetInteger64i_v(int pname, int index, LongBuffer params);
    long glGetInteger64i(int pname, int index);
    void glGetSynciv(long sync, int pname, IntBuffer length, IntBuffer values);
    int glGetSynci(long sync, int pname, IntBuffer length);
    void glGetBufferParameteri64v(int target, int pname, long[] params);
    // void glMultiDrawElementsBaseVertex(int mode, int[] count, int type, PointerBuffer indices, int[] basevertex);
    void glGetMultisamplefv(int pname, int index, float[] val);
    void glGetInteger64v(int pname, long[] params);
    void glGetInteger64i_v(int pname, int index, long[] params);
    void glGetSynciv(long sync, int pname, int[] length, int[] values);

}