package jpize.opengl.gl;

import java.nio.*;

public interface GLI45 extends GLI44 {

    int GL_NEGATIVE_ONE_TO_ONE = 37726;
    int GL_ZERO_TO_ONE = 37727;
    int GL_CLIP_ORIGIN = 37724;
    int GL_CLIP_DEPTH_MODE = 37725;
    int GL_QUERY_WAIT_INVERTED = 36375;
    int GL_QUERY_NO_WAIT_INVERTED = 36376;
    int GL_QUERY_BY_REGION_WAIT_INVERTED = 36377;
    int GL_QUERY_BY_REGION_NO_WAIT_INVERTED = 36378;
    int GL_MAX_CULL_DISTANCES = 33529;
    int GL_MAX_COMBINED_CLIP_AND_CULL_DISTANCES = 33530;
    int GL_TEXTURE_TARGET = 4102;
    int GL_QUERY_TARGET = 33514;
    int GL_CONTEXT_RELEASE_BEHAVIOR = 33531;
    int GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH = 33532;
    int GL_GUILTY_CONTEXT_RESET = 33363;
    int GL_INNOCENT_CONTEXT_RESET = 33364;
    int GL_UNKNOWN_CONTEXT_RESET = 33365;
    int GL_RESET_NOTIFICATION_STRATEGY = 33366;
    int GL_LOSE_CONTEXT_ON_RESET = 33362;
    int GL_NO_RESET_NOTIFICATION = 33377;
    int GL_CONTEXT_FLAG_ROBUST_ACCESS_BIT = 4;
    int GL_CONTEXT_LOST = 1287;

    void glClipControl(int origin, int depth);
    void glCreateTransformFeedbacks(IntBuffer ids);
    int glCreateTransformFeedbacks();
    void glTransformFeedbackBufferBase(int xfb, int index, int buffer);
    void glTransformFeedbackBufferRange(int xfb, int index, int buffer, long offset, long size);
    void glGetTransformFeedbackiv(int xfb, int pname, IntBuffer param);
    int glGetTransformFeedbacki(int xfb, int pname);
    void glGetTransformFeedbacki_v(int xfb, int pname, int index, IntBuffer param);
    int glGetTransformFeedbacki(int xfb, int pname, int index);
    void glGetTransformFeedbacki64_v(int xfb, int pname, int index, LongBuffer param);
    long glGetTransformFeedbacki64(int xfb, int pname, int index);
    void glCreateBuffers(IntBuffer buffers);
    int glCreateBuffers();
    void glNamedBufferStorage(int buffer, long size, int flags);
    void glNamedBufferStorage(int buffer, ByteBuffer data, int flags);
    void glNamedBufferStorage(int buffer, ShortBuffer data, int flags);
    void glNamedBufferStorage(int buffer, IntBuffer data, int flags);
    void glNamedBufferStorage(int buffer, FloatBuffer data, int flags);
    void glNamedBufferStorage(int buffer, DoubleBuffer data, int flags);
    void glNamedBufferData(int buffer, long size, int usage);
    void glNamedBufferData(int buffer, ByteBuffer data, int usage);
    void glNamedBufferData(int buffer, ShortBuffer data, int usage);
    void glNamedBufferData(int buffer, IntBuffer data, int usage);
    void glNamedBufferData(int buffer, LongBuffer data, int usage);
    void glNamedBufferData(int buffer, FloatBuffer data, int usage);
    void glNamedBufferData(int buffer, DoubleBuffer data, int usage);
    void glNamedBufferSubData(int buffer, long offset, ByteBuffer data);
    void glNamedBufferSubData(int buffer, long offset, ShortBuffer data);
    void glNamedBufferSubData(int buffer, long offset, IntBuffer data);
    void glNamedBufferSubData(int buffer, long offset, LongBuffer data);
    void glNamedBufferSubData(int buffer, long offset, FloatBuffer data);
    void glNamedBufferSubData(int buffer, long offset, DoubleBuffer data);
    void glCopyNamedBufferSubData(int readBuffer, int writeBuffer, long readOffset, long writeOffset, long size);
    void glClearNamedBufferData(int buffer, int internalformat, int format, int type, ByteBuffer data);
    void glClearNamedBufferData(int buffer, int internalformat, int format, int type, ShortBuffer data);
    void glClearNamedBufferData(int buffer, int internalformat, int format, int type, IntBuffer data);
    void glClearNamedBufferData(int buffer, int internalformat, int format, int type, FloatBuffer data);
    void glClearNamedBufferSubData(int buffer, int internalformat, long offset, long size, int format, int type, ByteBuffer data);
    void glClearNamedBufferSubData(int buffer, int internalformat, long offset, long size, int format, int type, ShortBuffer data);
    void glClearNamedBufferSubData(int buffer, int internalformat, long offset, long size, int format, int type, IntBuffer data);
    void glClearNamedBufferSubData(int buffer, int internalformat, long offset, long size, int format, int type, FloatBuffer data);
    ByteBuffer glMapNamedBuffer(int buffer, int access);
    ByteBuffer glMapNamedBuffer(int buffer, int access, ByteBuffer old_buffer);
    ByteBuffer glMapNamedBuffer(int buffer, int access, long length, ByteBuffer old_buffer);
    ByteBuffer glMapNamedBufferRange(int buffer, long offset, long length, int access);
    ByteBuffer glMapNamedBufferRange(int buffer, long offset, long length, int access, ByteBuffer old_buffer);
    boolean glUnmapNamedBuffer(int buffer);
    void glFlushMappedNamedBufferRange(int buffer, long offset, long length);
    void glGetNamedBufferParameteriv(int buffer, int pname, IntBuffer params);
    int glGetNamedBufferParameteri(int buffer, int pname);
    void glGetNamedBufferParameteri64v(int buffer, int pname, LongBuffer params);
    long glGetNamedBufferParameteri64(int buffer, int pname);
    // void glGetNamedBufferPointerv(int buffer, int pname, PointerBuffer params);
    long glGetNamedBufferPointer(int buffer, int pname);
    void glGetNamedBufferSubData(int buffer, long offset, ByteBuffer data);
    void glGetNamedBufferSubData(int buffer, long offset, ShortBuffer data);
    void glGetNamedBufferSubData(int buffer, long offset, IntBuffer data);
    void glGetNamedBufferSubData(int buffer, long offset, LongBuffer data);
    void glGetNamedBufferSubData(int buffer, long offset, FloatBuffer data);
    void glGetNamedBufferSubData(int buffer, long offset, DoubleBuffer data);
    void glCreateFramebuffers(IntBuffer framebuffers);
    int glCreateFramebuffers();
    void glNamedFramebufferRenderbuffer(int framebuffer, int attachment, int renderbuffertarget, int renderbuffer);
    void glNamedFramebufferParameteri(int framebuffer, int pname, int param);
    void glNamedFramebufferTexture(int framebuffer, int attachment, int texture, int level);
    void glNamedFramebufferTextureLayer(int framebuffer, int attachment, int texture, int level, int layer);
    void glNamedFramebufferDrawBuffer(int framebuffer, int buf);
    void glNamedFramebufferDrawBuffers(int framebuffer, IntBuffer bufs);
    void glNamedFramebufferDrawBuffers(int framebuffer, int buf);
    void glNamedFramebufferReadBuffer(int framebuffer, int src);
    void glInvalidateNamedFramebufferData(int framebuffer, IntBuffer attachments);
    void glInvalidateNamedFramebufferData(int framebuffer, int attachment);
    void glInvalidateNamedFramebufferSubData(int framebuffer, IntBuffer attachments, int x, int y, int width, int height);
    void glInvalidateNamedFramebufferSubData(int framebuffer, int attachment, int x, int y, int width, int height);
    void glClearNamedFramebufferiv(int framebuffer, int buffer, int drawbuffer, IntBuffer value);
    void glClearNamedFramebufferuiv(int framebuffer, int buffer, int drawbuffer, IntBuffer value);
    void glClearNamedFramebufferfv(int framebuffer, int buffer, int drawbuffer, FloatBuffer value);
    void glClearNamedFramebufferfi(int framebuffer, int buffer, int drawbuffer, float depth, int stencil);
    void glBlitNamedFramebuffer(int readFramebuffer, int drawFramebuffer, int srcX0, int srcY0, int srcX1, int srcY1, int dstX0, int dstY0, int dstX1, int dstY1, int mask, int filter);
    int glCheckNamedFramebufferStatus(int framebuffer, int target);
    void glGetNamedFramebufferParameteriv(int framebuffer, int pname, IntBuffer params);
    int glGetNamedFramebufferParameteri(int framebuffer, int pname);
    void glGetNamedFramebufferAttachmentParameteriv(int framebuffer, int attachment, int pname, IntBuffer params);
    int glGetNamedFramebufferAttachmentParameteri(int framebuffer, int attachment, int pname);
    void glCreateRenderbuffers(IntBuffer renderbuffers);
    int glCreateRenderbuffers();
    void glNamedRenderbufferStorage(int renderbuffer, int internalformat, int width, int height);
    void glNamedRenderbufferStorageMultisample(int renderbuffer, int samples, int internalformat, int width, int height);
    void glGetNamedRenderbufferParameteriv(int renderbuffer, int pname, IntBuffer params);
    int glGetNamedRenderbufferParameteri(int renderbuffer, int pname);
    void glCreateTextures(int target, IntBuffer textures);
    int glCreateTextures(int target);
    void glTextureBuffer(int texture, int internalformat, int buffer);
    void glTextureBufferRange(int texture, int internalformat, int buffer, long offset, long size);
    void glTextureStorage1D(int texture, int levels, int internalformat, int width);
    void glTextureStorage2D(int texture, int levels, int internalformat, int width, int height);
    void glTextureStorage3D(int texture, int levels, int internalformat, int width, int height, int depth);
    void glTextureStorage2DMultisample(int texture, int samples, int internalformat, int width, int height, boolean fixedsamplelocations);
    void glTextureStorage3DMultisample(int texture, int samples, int internalformat, int width, int height, int depth, boolean fixedsamplelocations);
    void glTextureSubImage1D(int texture, int level, int xoffset, int width, int format, int type, ByteBuffer pixels);
    void glTextureSubImage1D(int texture, int level, int xoffset, int width, int format, int type, long pixels);
    void glTextureSubImage1D(int texture, int level, int xoffset, int width, int format, int type, ShortBuffer pixels);
    void glTextureSubImage1D(int texture, int level, int xoffset, int width, int format, int type, IntBuffer pixels);
    void glTextureSubImage1D(int texture, int level, int xoffset, int width, int format, int type, FloatBuffer pixels);
    void glTextureSubImage1D(int texture, int level, int xoffset, int width, int format, int type, DoubleBuffer pixels);
    void glTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, int type, ByteBuffer pixels);
    void glTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, int type, long pixels);
    void glTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, int type, ShortBuffer pixels);
    void glTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, int type, IntBuffer pixels);
    void glTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, int type, FloatBuffer pixels);
    void glTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, int type, DoubleBuffer pixels);
    void glTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, ByteBuffer pixels);
    void glTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, long pixels);
    void glTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, ShortBuffer pixels);
    void glTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, IntBuffer pixels);
    void glTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, FloatBuffer pixels);
    void glTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, DoubleBuffer pixels);
    void glCompressedTextureSubImage1D(int texture, int level, int xoffset, int width, int format, int imageSize, long data);
    void glCompressedTextureSubImage1D(int texture, int level, int xoffset, int width, int format, ByteBuffer data);
    void glCompressedTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, int imageSize, long data);
    void glCompressedTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, ByteBuffer data);
    void glCompressedTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int imageSize, long data);
    void glCompressedTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, ByteBuffer data);
    void glCopyTextureSubImage1D(int texture, int level, int xoffset, int x, int y, int width);
    void glCopyTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int x, int y, int width, int height);
    void glCopyTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int x, int y, int width, int height);
    void glTextureParameterf(int texture, int pname, float param);
    void glTextureParameterfv(int texture, int pname, FloatBuffer params);
    void glTextureParameteri(int texture, int pname, int param);
    void glTextureParameterIiv(int texture, int pname, IntBuffer params);
    void glTextureParameterIi(int texture, int pname, int param);
    void glTextureParameterIuiv(int texture, int pname, IntBuffer params);
    void glTextureParameterIui(int texture, int pname, int param);
    void glTextureParameteriv(int texture, int pname, IntBuffer params);
    void glGenerateTextureMipmap(int texture);
    void glBindTextureUnit(int unit, int texture);
    void glGetTextureImage(int texture, int level, int format, int type, int bufSize, long pixels);
    void glGetTextureImage(int texture, int level, int format, int type, ByteBuffer pixels);
    void glGetTextureImage(int texture, int level, int format, int type, ShortBuffer pixels);
    void glGetTextureImage(int texture, int level, int format, int type, IntBuffer pixels);
    void glGetTextureImage(int texture, int level, int format, int type, FloatBuffer pixels);
    void glGetTextureImage(int texture, int level, int format, int type, DoubleBuffer pixels);
    void glGetCompressedTextureImage(int texture, int level, int bufSize, long pixels);
    void glGetCompressedTextureImage(int texture, int level, ByteBuffer pixels);
    void glGetTextureLevelParameterfv(int texture, int level, int pname, FloatBuffer params);
    float glGetTextureLevelParameterf(int texture, int level, int pname);
    void glGetTextureLevelParameteriv(int texture, int level, int pname, IntBuffer params);
    int glGetTextureLevelParameteri(int texture, int level, int pname);
    void glGetTextureParameterfv(int texture, int pname, FloatBuffer params);
    float glGetTextureParameterf(int texture, int pname);
    void glGetTextureParameterIiv(int texture, int pname, IntBuffer params);
    int glGetTextureParameterIi(int texture, int pname);
    void glGetTextureParameterIuiv(int texture, int pname, IntBuffer params);
    int glGetTextureParameterIui(int texture, int pname);
    void glGetTextureParameteriv(int texture, int pname, IntBuffer params);
    int glGetTextureParameteri(int texture, int pname);
    void glCreateVertexArrays(IntBuffer arrays);
    int glCreateVertexArrays();
    void glDisableVertexArrayAttrib(int vaobj, int index);
    void glEnableVertexArrayAttrib(int vaobj, int index);
    void glVertexArrayElementBuffer(int vaobj, int buffer);
    void glVertexArrayVertexBuffer(int vaobj, int bindingindex, int buffer, long offset, int stride);
    // void glVertexArrayVertexBuffers(int vaobj, int first, IntBuffer buffers, PointerBuffer offsets, IntBuffer strides);
    void glVertexArrayAttribFormat(int vaobj, int attribindex, int size, int type, boolean normalized, int relativeoffset);
    void glVertexArrayAttribIFormat(int vaobj, int attribindex, int size, int type, int relativeoffset);
    void glVertexArrayAttribLFormat(int vaobj, int attribindex, int size, int type, int relativeoffset);
    void glVertexArrayAttribBinding(int vaobj, int attribindex, int bindingindex);
    void glVertexArrayBindingDivisor(int vaobj, int bindingindex, int divisor);
    void glGetVertexArrayiv(int vaobj, int pname, IntBuffer param);
    int glGetVertexArrayi(int vaobj, int pname);
    void glGetVertexArrayIndexediv(int vaobj, int index, int pname, IntBuffer param);
    int glGetVertexArrayIndexedi(int vaobj, int index, int pname);
    void glGetVertexArrayIndexed64iv(int vaobj, int index, int pname, LongBuffer param);
    long glGetVertexArrayIndexed64i(int vaobj, int index, int pname);
    void glCreateSamplers(IntBuffer samplers);
    int glCreateSamplers();
    void glCreateProgramPipelines(IntBuffer pipelines);
    int glCreateProgramPipelines();
    void glCreateQueries(int target, IntBuffer ids);
    int glCreateQueries(int target);
    void glGetQueryBufferObjectiv(int id, int buffer, int pname, long offset);
    void glGetQueryBufferObjectuiv(int id, int buffer, int pname, long offset);
    void glGetQueryBufferObjecti64v(int id, int buffer, int pname, long offset);
    void glGetQueryBufferObjectui64v(int id, int buffer, int pname, long offset);
    void glMemoryBarrierByRegion(int barriers);
    void glGetTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, int bufSize, long pixels);
    void glGetTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, ByteBuffer pixels);
    void glGetTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, ShortBuffer pixels);
    void glGetTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, IntBuffer pixels);
    void glGetTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, FloatBuffer pixels);
    void glGetTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, DoubleBuffer pixels);
    void glGetCompressedTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int bufSize, long pixels);
    void glGetCompressedTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, ByteBuffer pixels);
    void glGetCompressedTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, ShortBuffer pixels);
    void glGetCompressedTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, IntBuffer pixels);
    void glGetCompressedTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, FloatBuffer pixels);
    void glGetCompressedTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, DoubleBuffer pixels);
    void glTextureBarrier();
    int glGetGraphicsResetStatus();
    void glGetnMapdv(int target, int query, DoubleBuffer data);
    double glGetnMapd(int target, int query);
    void glGetnMapfv(int target, int query, FloatBuffer data);
    float glGetnMapf(int target, int query);
    void glGetnMapiv(int target, int query, IntBuffer data);
    int glGetnMapi(int target, int query);
    void glGetnPixelMapfv(int map, FloatBuffer data);
    void glGetnPixelMapuiv(int map, IntBuffer data);
    void glGetnPixelMapusv(int map, ShortBuffer data);
    void glGetnPolygonStipple(int bufSize, long pattern);
    void glGetnPolygonStipple(ByteBuffer pattern);
    void glGetnTexImage(int tex, int level, int format, int type, int bufSize, long img);
    void glGetnTexImage(int tex, int level, int format, int type, ByteBuffer img);
    void glGetnTexImage(int tex, int level, int format, int type, ShortBuffer img);
    void glGetnTexImage(int tex, int level, int format, int type, IntBuffer img);
    void glGetnTexImage(int tex, int level, int format, int type, FloatBuffer img);
    void glGetnTexImage(int tex, int level, int format, int type, DoubleBuffer img);
    void glReadnPixels(int x, int y, int width, int height, int format, int type, int bufSize, long pixels);
    void glReadnPixels(int x, int y, int width, int height, int format, int type, ByteBuffer pixels);
    void glReadnPixels(int x, int y, int width, int height, int format, int type, ShortBuffer pixels);
    void glReadnPixels(int x, int y, int width, int height, int format, int type, IntBuffer pixels);
    void glReadnPixels(int x, int y, int width, int height, int format, int type, FloatBuffer pixels);
    void glGetnColorTable(int target, int format, int type, int bufSize, long table);
    void glGetnColorTable(int target, int format, int type, ByteBuffer table);
    void glGetnColorTable(int target, int format, int type, ShortBuffer table);
    void glGetnColorTable(int target, int format, int type, IntBuffer table);
    void glGetnColorTable(int target, int format, int type, FloatBuffer table);
    void glGetnConvolutionFilter(int target, int format, int type, int bufSize, long image);
    void glGetnConvolutionFilter(int target, int format, int type, ByteBuffer image);
    void glGetnSeparableFilter(int target, int format, int type, int rowBufSize, long row, int columnBufSize, long column, ByteBuffer span);
    void glGetnSeparableFilter(int target, int format, int type, ByteBuffer row, ByteBuffer column, ByteBuffer span);
    void glGetnHistogram(int target, boolean reset, int format, int type, int bufSize, long values);
    void glGetnHistogram(int target, boolean reset, int format, int type, ByteBuffer values);
    void glGetnMinmax(int target, boolean reset, int format, int type, int bufSize, long values);
    void glGetnMinmax(int target, boolean reset, int format, int type, ByteBuffer values);
    void glGetnCompressedTexImage(int target, int level, int bufSize, long img);
    void glGetnCompressedTexImage(int target, int level, ByteBuffer img);
    void glGetnUniformfv(int program, int location, FloatBuffer params);
    float glGetnUniformf(int program, int location);
    void glGetnUniformdv(int program, int location, DoubleBuffer params);
    double glGetnUniformd(int program, int location);
    void glGetnUniformiv(int program, int location, IntBuffer params);
    int glGetnUniformi(int program, int location);
    void glGetnUniformuiv(int program, int location, IntBuffer params);
    int glGetnUniformui(int program, int location);
    void glCreateTransformFeedbacks(int[] ids);
    void glGetTransformFeedbackiv(int xfb, int pname, int[] param);
    void glGetTransformFeedbacki_v(int xfb, int pname, int index, int[] param);
    void glGetTransformFeedbacki64_v(int xfb, int pname, int index, long[] param);
    void glCreateBuffers(int[] buffers);
    void glNamedBufferStorage(int buffer, short[] data, int flags);
    void glNamedBufferStorage(int buffer, int[] data, int flags);
    void glNamedBufferStorage(int buffer, float[] data, int flags);
    void glNamedBufferStorage(int buffer, double[] data, int flags);
    void glNamedBufferData(int buffer, short[] data, int usage);
    void glNamedBufferData(int buffer, int[] data, int usage);
    void glNamedBufferData(int buffer, long[] data, int usage);
    void glNamedBufferData(int buffer, float[] data, int usage);
    void glNamedBufferData(int buffer, double[] data, int usage);
    void glNamedBufferSubData(int buffer, long offset, short[] data);
    void glNamedBufferSubData(int buffer, long offset, int[] data);
    void glNamedBufferSubData(int buffer, long offset, long[] data);
    void glNamedBufferSubData(int buffer, long offset, float[] data);
    void glNamedBufferSubData(int buffer, long offset, double[] data);
    void glClearNamedBufferData(int buffer, int internalformat, int format, int type, short[] data);
    void glClearNamedBufferData(int buffer, int internalformat, int format, int type, int[] data);
    void glClearNamedBufferData(int buffer, int internalformat, int format, int type, float[] data);
    void glClearNamedBufferSubData(int buffer, int internalformat, long offset, long size, int format, int type, short[] data);
    void glClearNamedBufferSubData(int buffer, int internalformat, long offset, long size, int format, int type, int[] data);
    void glClearNamedBufferSubData(int buffer, int internalformat, long offset, long size, int format, int type, float[] data);
    void glGetNamedBufferParameteriv(int buffer, int pname, int[] params);
    void glGetNamedBufferParameteri64v(int buffer, int pname, long[] params);
    void glGetNamedBufferSubData(int buffer, long offset, short[] data);
    void glGetNamedBufferSubData(int buffer, long offset, int[] data);
    void glGetNamedBufferSubData(int buffer, long offset, long[] data);
    void glGetNamedBufferSubData(int buffer, long offset, float[] data);
    void glGetNamedBufferSubData(int buffer, long offset, double[] data);
    void glCreateFramebuffers(int[] framebuffers);
    void glNamedFramebufferDrawBuffers(int framebuffer, int[] bufs);
    void glInvalidateNamedFramebufferData(int framebuffer, int[] attachments);
    void glInvalidateNamedFramebufferSubData(int framebuffer, int[] attachments, int x, int y, int width, int height);
    void glClearNamedFramebufferiv(int framebuffer, int buffer, int drawbuffer, int[] value);
    void glClearNamedFramebufferuiv(int framebuffer, int buffer, int drawbuffer, int[] value);
    void glClearNamedFramebufferfv(int framebuffer, int buffer, int drawbuffer, float[] value);
    void glGetNamedFramebufferParameteriv(int framebuffer, int pname, int[] params);
    void glGetNamedFramebufferAttachmentParameteriv(int framebuffer, int attachment, int pname, int[] params);
    void glCreateRenderbuffers(int[] renderbuffers);
    void glGetNamedRenderbufferParameteriv(int renderbuffer, int pname, int[] params);
    void glCreateTextures(int target, int[] textures);
    void glTextureSubImage1D(int texture, int level, int xoffset, int width, int format, int type, short[] pixels);
    void glTextureSubImage1D(int texture, int level, int xoffset, int width, int format, int type, int[] pixels);
    void glTextureSubImage1D(int texture, int level, int xoffset, int width, int format, int type, float[] pixels);
    void glTextureSubImage1D(int texture, int level, int xoffset, int width, int format, int type, double[] pixels);
    void glTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, int type, short[] pixels);
    void glTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, int type, int[] pixels);
    void glTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, int type, float[] pixels);
    void glTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, int type, double[] pixels);
    void glTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, short[] pixels);
    void glTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, int[] pixels);
    void glTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, float[] pixels);
    void glTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, double[] pixels);
    void glTextureParameterfv(int texture, int pname, float[] params);
    void glTextureParameterIiv(int texture, int pname, int[] params);
    void glTextureParameterIuiv(int texture, int pname, int[] params);
    void glTextureParameteriv(int texture, int pname, int[] params);
    void glGetTextureImage(int texture, int level, int format, int type, short[] pixels);
    void glGetTextureImage(int texture, int level, int format, int type, int[] pixels);
    void glGetTextureImage(int texture, int level, int format, int type, float[] pixels);
    void glGetTextureImage(int texture, int level, int format, int type, double[] pixels);
    void glGetTextureLevelParameterfv(int texture, int level, int pname, float[] params);
    void glGetTextureLevelParameteriv(int texture, int level, int pname, int[] params);
    void glGetTextureParameterfv(int texture, int pname, float[] params);
    void glGetTextureParameterIiv(int texture, int pname, int[] params);
    void glGetTextureParameterIuiv(int texture, int pname, int[] params);
    void glGetTextureParameteriv(int texture, int pname, int[] params);
    void glCreateVertexArrays(int[] arrays);
    // void glVertexArrayVertexBuffers(int vaobj, int first, int[] buffers, PointerBuffer offsets, int[] strides);
    void glGetVertexArrayiv(int vaobj, int pname, int[] param);
    void glGetVertexArrayIndexediv(int vaobj, int index, int pname, int[] param);
    void glGetVertexArrayIndexed64iv(int vaobj, int index, int pname, long[] param);
    void glCreateSamplers(int[] samplers);
    void glCreateProgramPipelines(int[] pipelines);
    void glCreateQueries(int target, int[] ids);
    void glGetTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, short[] pixels);
    void glGetTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, int[] pixels);
    void glGetTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, float[] pixels);
    void glGetTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, double[] pixels);
    void glGetCompressedTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, short[] pixels);
    void glGetCompressedTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int[] pixels);
    void glGetCompressedTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, float[] pixels);
    void glGetCompressedTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, double[] pixels);
    void glGetnMapdv(int target, int query, double[] data);
    void glGetnMapfv(int target, int query, float[] data);
    void glGetnMapiv(int target, int query, int[] data);
    void glGetnPixelMapfv(int map, float[] data);
    void glGetnPixelMapuiv(int map, int[] data);
    void glGetnPixelMapusv(int map, short[] data);
    void glGetnTexImage(int tex, int level, int format, int type, short[] img);
    void glGetnTexImage(int tex, int level, int format, int type, int[] img);
    void glGetnTexImage(int tex, int level, int format, int type, float[] img);
    void glGetnTexImage(int tex, int level, int format, int type, double[] img);
    void glReadnPixels(int x, int y, int width, int height, int format, int type, short[] pixels);
    void glReadnPixels(int x, int y, int width, int height, int format, int type, int[] pixels);
    void glReadnPixels(int x, int y, int width, int height, int format, int type, float[] pixels);
    void glGetnColorTable(int target, int format, int type, short[] table);
    void glGetnColorTable(int target, int format, int type, int[] table);
    void glGetnColorTable(int target, int format, int type, float[] table);
    void glGetnUniformfv(int program, int location, float[] params);
    void glGetnUniformdv(int program, int location, double[] params);
    void glGetnUniformiv(int program, int location, int[] params);
    void glGetnUniformuiv(int program, int location, int[] params);
    
}
