package jpize.opengl.gl;

import java.nio.*;

public interface IGL14 extends IGL13 {

    int GL_GENERATE_MIPMAP = 33169;
    int GL_GENERATE_MIPMAP_HINT = 33170;
    int GL_CONSTANT_COLOR = 32769;
    int GL_ONE_MINUS_CONSTANT_COLOR = 32770;
    int GL_CONSTANT_ALPHA = 32771;
    int GL_ONE_MINUS_CONSTANT_ALPHA = 32772;
    int GL_BLEND_COLOR = 32773;
    int GL_FUNC_ADD = 32774;
    int GL_MIN = 32775;
    int GL_MAX = 32776;
    int GL_BLEND_EQUATION = 32777;
    int GL_FUNC_SUBTRACT = 32778;
    int GL_FUNC_REVERSE_SUBTRACT = 32779;
    int GL_DEPTH_COMPONENT16 = 33189;
    int GL_DEPTH_COMPONENT24 = 33190;
    int GL_DEPTH_COMPONENT32 = 33191;
    int GL_TEXTURE_DEPTH_SIZE = 34890;
    int GL_DEPTH_TEXTURE_MODE = 34891;
    int GL_TEXTURE_COMPARE_MODE = 34892;
    int GL_TEXTURE_COMPARE_FUNC = 34893;
    int GL_COMPARE_R_TO_TEXTURE = 34894;
    int GL_FOG_COORDINATE_SOURCE = 33872;
    int GL_FOG_COORDINATE = 33873;
    int GL_FRAGMENT_DEPTH = 33874;
    int GL_CURRENT_FOG_COORDINATE = 33875;
    int GL_FOG_COORDINATE_ARRAY_TYPE = 33876;
    int GL_FOG_COORDINATE_ARRAY_STRIDE = 33877;
    int GL_FOG_COORDINATE_ARRAY_POINTER = 33878;
    int GL_FOG_COORDINATE_ARRAY = 33879;
    int GL_POINT_SIZE_MIN = 33062;
    int GL_POINT_SIZE_MAX = 33063;
    int GL_POINT_FADE_THRESHOLD_SIZE = 33064;
    int GL_POINT_DISTANCE_ATTENUATION = 33065;
    int GL_COLOR_SUM = 33880;
    int GL_CURRENT_SECONDARY_COLOR = 33881;
    int GL_SECONDARY_COLOR_ARRAY_SIZE = 33882;
    int GL_SECONDARY_COLOR_ARRAY_TYPE = 33883;
    int GL_SECONDARY_COLOR_ARRAY_STRIDE = 33884;
    int GL_SECONDARY_COLOR_ARRAY_POINTER = 33885;
    int GL_SECONDARY_COLOR_ARRAY = 33886;
    int GL_BLEND_DST_RGB = 32968;
    int GL_BLEND_SRC_RGB = 32969;
    int GL_BLEND_DST_ALPHA = 32970;
    int GL_BLEND_SRC_ALPHA = 32971;
    int GL_INCR_WRAP = 34055;
    int GL_DECR_WRAP = 34056;
    int GL_TEXTURE_FILTER_CONTROL = 34048;
    int GL_TEXTURE_LOD_BIAS = 34049;
    int GL_MAX_TEXTURE_LOD_BIAS = 34045;
    int GL_MIRRORED_REPEAT = 33648;

    void glBlendColor(float red, float green, float blue, float alpha);
    void glBlendEquation(int mode);
    void glFogCoordf(float var0);
    void glFogCoordd(double var0);
    void nglFogCoordfv(long var0);
    void glFogCoordfv(FloatBuffer coord);
    void nglFogCoorddv(long var0);
    void glFogCoorddv(DoubleBuffer coord);
    void nglFogCoordPointer(int var0, int var1, long var2);
    void glFogCoordPointer(int type, int stride, ByteBuffer pointer);
    void glFogCoordPointer(int type, int stride, long pointer);
    void glFogCoordPointer(int type, int stride, ShortBuffer pointer);
    void glFogCoordPointer(int type, int stride, FloatBuffer pointer);
    void nglMultiDrawArrays(int mode, long first, long count, int drawcount);
    void glMultiDrawArrays(int mode, IntBuffer first, IntBuffer count);
    void nglMultiDrawElements(int mode, long count, int type, long indices, int drawcount);
    // void glMultiDrawElements(int mode, IntBuffer count, int type, PointerBuffer indices);
    void glPointParameterf(int pname, float param);
    void glPointParameteri(int pname, int param);
    void nglPointParameterfv(int pname, long params);
    void glPointParameterfv(int pname, FloatBuffer params);
    void nglPointParameteriv(int pname, long params);
    void glPointParameteriv(int pname, IntBuffer params);
    void glSecondaryColor3b(byte var0, byte var1, byte var2);
    void glSecondaryColor3s(short var0, short var1, short var2);
    void glSecondaryColor3i(int var0, int var1, int var2);
    void glSecondaryColor3f(float var0, float var1, float var2);
    void glSecondaryColor3d(double var0, double var2, double var4);
    void glSecondaryColor3ub(byte var0, byte var1, byte var2);
    void glSecondaryColor3us(short var0, short var1, short var2);
    void glSecondaryColor3ui(int var0, int var1, int var2);
    void nglSecondaryColor3bv(long var0);
    void glSecondaryColor3bv(ByteBuffer v);
    void nglSecondaryColor3sv(long var0);
    void glSecondaryColor3sv(ShortBuffer v);
    void nglSecondaryColor3iv(long var0);
    void glSecondaryColor3iv(IntBuffer v);
    void nglSecondaryColor3fv(long var0);
    void glSecondaryColor3fv(FloatBuffer v);
    void nglSecondaryColor3dv(long var0);
    void glSecondaryColor3dv(DoubleBuffer v);
    void nglSecondaryColor3ubv(long var0);
    void glSecondaryColor3ubv(ByteBuffer v);
    void nglSecondaryColor3usv(long var0);
    void glSecondaryColor3usv(ShortBuffer v);
    void nglSecondaryColor3uiv(long var0);
    void glSecondaryColor3uiv(IntBuffer v);
    void nglSecondaryColorPointer(int var0, int var1, int var2, long var3);
    void glSecondaryColorPointer(int size, int type, int stride, ByteBuffer pointer);
    void glSecondaryColorPointer(int size, int type, int stride, long pointer);
    void glSecondaryColorPointer(int size, int type, int stride, ShortBuffer pointer);
    void glSecondaryColorPointer(int size, int type, int stride, IntBuffer pointer);
    void glSecondaryColorPointer(int size, int type, int stride, FloatBuffer pointer);
    void glBlendFuncSeparate(int sfactorRGB, int dfactorRGB, int sfactorAlpha, int dfactorAlpha);
    void glWindowPos2i(int var0, int var1);
    void glWindowPos2s(short var0, short var1);
    void glWindowPos2f(float var0, float var1);
    void glWindowPos2d(double var0, double var2);
    void nglWindowPos2iv(long var0);
    void glWindowPos2iv(IntBuffer p);
    void nglWindowPos2sv(long var0);
    void glWindowPos2sv(ShortBuffer p);
    void nglWindowPos2fv(long var0);
    void glWindowPos2fv(FloatBuffer p);
    void nglWindowPos2dv(long var0);
    void glWindowPos2dv(DoubleBuffer p);
    void glWindowPos3i(int var0, int var1, int var2);
    void glWindowPos3s(short var0, short var1, short var2);
    void glWindowPos3f(float var0, float var1, float var2);
    void glWindowPos3d(double var0, double var2, double var4);
    void nglWindowPos3iv(long var0);
    void glWindowPos3iv(IntBuffer p);
    void nglWindowPos3sv(long var0);
    void glWindowPos3sv(ShortBuffer p);
    void nglWindowPos3fv(long var0);
    void glWindowPos3fv(FloatBuffer p);
    void nglWindowPos3dv(long var0);
    void glWindowPos3dv(DoubleBuffer p);
    void glFogCoordfv(float[] coord);
    void glFogCoorddv(double[] coord);
    void glMultiDrawArrays(int mode, int[] first, int[] count);
    // void glMultiDrawElements(int mode, int[] count, int type, PointerBuffer indices);
    void glPointParameterfv(int pname, float[] params);
    void glPointParameteriv(int pname, int[] params);
    void glSecondaryColor3sv(short[] v);
    void glSecondaryColor3iv(int[] v);
    void glSecondaryColor3fv(float[] v);
    void glSecondaryColor3dv(double[] v);
    void glSecondaryColor3usv(short[] v);
    void glSecondaryColor3uiv(int[] v);
    void glWindowPos2iv(int[] p);
    void glWindowPos2sv(short[] p);
    void glWindowPos2fv(float[] p);
    void glWindowPos2dv(double[] p);
    void glWindowPos3iv(int[] p);
    void glWindowPos3sv(short[] p);
    void glWindowPos3fv(float[] p);
    void glWindowPos3dv(double[] p);
    
}
