/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jpize_stb_freetype_FreeTypeSizeMetrics */

#ifndef _Included_jpize_stb_freetype_FreeTypeSizeMetrics
#define _Included_jpize_stb_freetype_FreeTypeSizeMetrics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jpize_stb_freetype_FreeTypeSizeMetrics
 * Method:    getXppem
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeSizeMetrics_getXppem
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeSizeMetrics
 * Method:    getYppem
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeSizeMetrics_getYppem
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeSizeMetrics
 * Method:    getXscale
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeSizeMetrics_getXscale
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeSizeMetrics
 * Method:    getYscale
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeSizeMetrics_getYscale
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeSizeMetrics
 * Method:    getAscender
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeSizeMetrics_getAscender
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeSizeMetrics
 * Method:    getDescender
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeSizeMetrics_getDescender
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeSizeMetrics
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeSizeMetrics_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeSizeMetrics
 * Method:    getMaxAdvance
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeSizeMetrics_getMaxAdvance
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
