/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jpize_stb_freetype_FreeTypeStroker */

#ifndef _Included_jpize_stb_freetype_FreeTypeStroker
#define _Included_jpize_stb_freetype_FreeTypeStroker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jpize_stb_freetype_FreeTypeStroker
 * Method:    set
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_jpize_stb_freetype_FreeTypeStroker_set
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     jpize_stb_freetype_FreeTypeStroker
 * Method:    done
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jpize_stb_freetype_FreeTypeStroker_done
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
