/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jpize_stb_freetype_FreeTypeGlyph */

#ifndef _Included_jpize_stb_freetype_FreeTypeGlyph
#define _Included_jpize_stb_freetype_FreeTypeGlyph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jpize_stb_freetype_FreeTypeGlyph
 * Method:    strokeBorder
 * Signature: (JJZ)J
 */
JNIEXPORT jlong JNICALL Java_jpize_stb_freetype_FreeTypeGlyph_strokeBorder
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyph
 * Method:    toBitmap
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_jpize_stb_freetype_FreeTypeGlyph_toBitmap
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyph
 * Method:    getBitmap
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jpize_stb_freetype_FreeTypeGlyph_getBitmap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyph
 * Method:    getLeft
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeGlyph_getLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyph
 * Method:    getTop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeGlyph_getTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyph
 * Method:    done
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jpize_stb_freetype_FreeTypeGlyph_done
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
