/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jpize_stb_freetype_FreeTypeGlyphMetrics */

#ifndef _Included_jpize_stb_freetype_FreeTypeGlyphMetrics
#define _Included_jpize_stb_freetype_FreeTypeGlyphMetrics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jpize_stb_freetype_FreeTypeGlyphMetrics
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeGlyphMetrics_getWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyphMetrics
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeGlyphMetrics_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyphMetrics
 * Method:    getHoriBearingX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeGlyphMetrics_getHoriBearingX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyphMetrics
 * Method:    getHoriBearingY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeGlyphMetrics_getHoriBearingY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyphMetrics
 * Method:    getHoriAdvance
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeGlyphMetrics_getHoriAdvance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyphMetrics
 * Method:    getVertBearingX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeGlyphMetrics_getVertBearingX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyphMetrics
 * Method:    getVertBearingY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeGlyphMetrics_getVertBearingY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyphMetrics
 * Method:    getVertAdvance
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeGlyphMetrics_getVertAdvance
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
