package jpize.gl;

import java.nio.FloatBuffer;
import java.nio.IntBuffer;

public interface IGL31 extends IGL30 {
    
    int GL_VERTEX_SHADER_BIT = 1;
    int GL_FRAGMENT_SHADER_BIT = 2;
    int GL_COMPUTE_SHADER_BIT = 32;
    int GL_ALL_SHADER_BITS = -1;
    int GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT = 1;
    int GL_ELEMENT_ARRAY_BARRIER_BIT = 2;
    int GL_UNIFORM_BARRIER_BIT = 4;
    int GL_TEXTURE_FETCH_BARRIER_BIT = 8;
    int GL_SHADER_IMAGE_ACCESS_BARRIER_BIT = 32;
    int GL_COMMAND_BARRIER_BIT = 64;
    int GL_PIXEL_BUFFER_BARRIER_BIT = 128;
    int GL_TEXTURE_UPDATE_BARRIER_BIT = 256;
    int GL_BUFFER_UPDATE_BARRIER_BIT = 512;
    int GL_FRAMEBUFFER_BARRIER_BIT = 1024;
    int GL_TRANSFORM_FEEDBACK_BARRIER_BIT = 2048;
    int GL_ATOMIC_COUNTER_BARRIER_BIT = 4096;
    int GL_SHADER_STORAGE_BARRIER_BIT = 8192;
    int GL_ALL_BARRIER_BITS = -1;
    int GL_TEXTURE_WIDTH = 4096;
    int GL_TEXTURE_HEIGHT = 4097;
    int GL_TEXTURE_INTERNAL_FORMAT = 4099;
    int GL_STENCIL_INDEX = 6401;
    int GL_TEXTURE_RED_SIZE = 32860;
    int GL_TEXTURE_GREEN_SIZE = 32861;
    int GL_TEXTURE_BLUE_SIZE = 32862;
    int GL_TEXTURE_ALPHA_SIZE = 32863;
    int GL_TEXTURE_DEPTH = 32881;
    int GL_PROGRAM_SEPARABLE = 33368;
    int GL_ACTIVE_PROGRAM = 33369;
    int GL_PROGRAM_PIPELINE_BINDING = 33370;
    int GL_MAX_COMPUTE_SHARED_MEMORY_SIZE = 33378;
    int GL_MAX_COMPUTE_UNIFORM_COMPONENTS = 33379;
    int GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS = 33380;
    int GL_MAX_COMPUTE_ATOMIC_COUNTERS = 33381;
    int GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS = 33382;
    int GL_COMPUTE_WORK_GROUP_SIZE = 33383;
    int GL_MAX_UNIFORM_LOCATIONS = 33390;
    int GL_VERTEX_ATTRIB_BINDING = 33492;
    int GL_VERTEX_ATTRIB_RELATIVE_OFFSET = 33493;
    int GL_VERTEX_BINDING_DIVISOR = 33494;
    int GL_VERTEX_BINDING_OFFSET = 33495;
    int GL_VERTEX_BINDING_STRIDE = 33496;
    int GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET = 33497;
    int GL_MAX_VERTEX_ATTRIB_BINDINGS = 33498;
    int GL_MAX_VERTEX_ATTRIB_STRIDE = 33509;
    int GL_TEXTURE_COMPRESSED = 34465;
    int GL_TEXTURE_DEPTH_SIZE = 34890;
    int GL_READ_ONLY  = 35000;
    int GL_WRITE_ONLY = 35001;
    int GL_READ_WRITE = 35002;
    int GL_TEXTURE_STENCIL_SIZE = 35057;
    int GL_TEXTURE_RED_TYPE = 35856;
    int GL_TEXTURE_GREEN_TYPE = 35857;
    int GL_TEXTURE_BLUE_TYPE = 35858;
    int GL_TEXTURE_ALPHA_TYPE = 35859;
    int GL_TEXTURE_DEPTH_TYPE = 35862;
    int GL_TEXTURE_SHARED_SIZE = 35903;
    int GL_SAMPLE_POSITION = 36432;
    int GL_SAMPLE_MASK = 36433;
    int GL_SAMPLE_MASK_VALUE = 36434;
    int GL_MAX_SAMPLE_MASK_WORDS = 36441;
    int GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET = 36446;
    int GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET = 36447;
    int GL_MAX_IMAGE_UNITS = 36664;
    int GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES = 36665;
    int GL_IMAGE_BINDING_NAME = 36666;
    int GL_IMAGE_BINDING_LEVEL = 36667;
    int GL_IMAGE_BINDING_LAYERED = 36668;
    int GL_IMAGE_BINDING_LAYER = 36669;
    int GL_IMAGE_BINDING_ACCESS = 36670;
    int GL_DRAW_INDIRECT_BUFFER = 36671;
    int GL_DRAW_INDIRECT_BUFFER_BINDING = 36675;
    int GL_VERTEX_BINDING_BUFFER = 36687;
    int GL_IMAGE_2D = 36941;
    int GL_IMAGE_3D = 36942;
    int GL_IMAGE_CUBE = 36944;
    int GL_IMAGE_2D_ARRAY = 36947;
    int GL_INT_IMAGE_2D = 36952;
    int GL_INT_IMAGE_3D = 36953;
    int GL_INT_IMAGE_CUBE = 36955;
    int GL_INT_IMAGE_2D_ARRAY = 36958;
    int GL_UNSIGNED_INT_IMAGE_2D = 36963;
    int GL_UNSIGNED_INT_IMAGE_3D = 36964;
    int GL_UNSIGNED_INT_IMAGE_CUBE = 36966;
    int GL_UNSIGNED_INT_IMAGE_2D_ARRAY = 36969;
    int GL_IMAGE_BINDING_FORMAT = 36974;
    int GL_IMAGE_FORMAT_COMPATIBILITY_TYPE = 37063;
    int GL_IMAGE_FORMAT_COMPATIBILITY_BY_SIZE = 37064;
    int GL_IMAGE_FORMAT_COMPATIBILITY_BY_CLASS = 37065;
    int GL_MAX_VERTEX_IMAGE_UNIFORMS = 37066;
    int GL_MAX_FRAGMENT_IMAGE_UNIFORMS = 37070;
    int GL_MAX_COMBINED_IMAGE_UNIFORMS = 37071;
    int GL_SHADER_STORAGE_BUFFER = 37074;
    int GL_SHADER_STORAGE_BUFFER_BINDING = 37075;
    int GL_SHADER_STORAGE_BUFFER_START = 37076;
    int GL_SHADER_STORAGE_BUFFER_SIZE = 37077;
    int GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS = 37078;
    int GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS = 37082;
    int GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS = 37083;
    int GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS = 37084;
    int GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS = 37085;
    int GL_MAX_SHADER_STORAGE_BLOCK_SIZE = 37086;
    int GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT = 37087;
    int GL_DEPTH_STENCIL_TEXTURE_MODE = 37098;
    int GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS = 37099;
    int GL_DISPATCH_INDIRECT_BUFFER = 37102;
    int GL_DISPATCH_INDIRECT_BUFFER_BINDING = 37103;
    int GL_TEXTURE_2D_MULTISAMPLE = 37120;
    int GL_TEXTURE_BINDING_2D_MULTISAMPLE = 37124;
    int GL_TEXTURE_SAMPLES = 37126;
    int GL_TEXTURE_FIXED_SAMPLE_LOCATIONS = 37127;
    int GL_SAMPLER_2D_MULTISAMPLE = 37128;
    int GL_INT_SAMPLER_2D_MULTISAMPLE = 37129;
    int GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE = 37130;
    int GL_MAX_COLOR_TEXTURE_SAMPLES = 37134;
    int GL_MAX_DEPTH_TEXTURE_SAMPLES = 37135;
    int GL_MAX_INTEGER_SAMPLES = 37136;
    int GL_COMPUTE_SHADER = 37305;
    int GL_MAX_COMPUTE_UNIFORM_BLOCKS = 37307;
    int GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS = 37308;
    int GL_MAX_COMPUTE_IMAGE_UNIFORMS = 37309;
    int GL_MAX_COMPUTE_WORK_GROUP_COUNT = 37310;
    int GL_MAX_COMPUTE_WORK_GROUP_SIZE = 37311;
    int GL_ATOMIC_COUNTER_BUFFER = 37568;
    int GL_ATOMIC_COUNTER_BUFFER_BINDING = 37569;
    int GL_ATOMIC_COUNTER_BUFFER_START = 37570;
    int GL_ATOMIC_COUNTER_BUFFER_SIZE = 37571;
    int GL_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS = 37580;
    int GL_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS = 37584;
    int GL_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS = 37585;
    int GL_MAX_VERTEX_ATOMIC_COUNTERS = 37586;
    int GL_MAX_FRAGMENT_ATOMIC_COUNTERS = 37590;
    int GL_MAX_COMBINED_ATOMIC_COUNTERS = 37591;
    int GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE = 37592;
    int GL_ACTIVE_ATOMIC_COUNTER_BUFFERS = 37593;
    int GL_UNSIGNED_INT_ATOMIC_COUNTER = 37595;
    int GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS = 37596;
    int GL_UNIFORM = 37601;
    int GL_UNIFORM_BLOCK = 37602;
    int GL_PROGRAM_INPUT = 37603;
    int GL_PROGRAM_OUTPUT = 37604;
    int GL_BUFFER_VARIABLE = 37605;
    int GL_SHADER_STORAGE_BLOCK = 37606;
    int GL_TRANSFORM_FEEDBACK_VARYING = 37620;
    int GL_ACTIVE_RESOURCES = 37621;
    int GL_MAX_NAME_LENGTH = 37622;
    int GL_MAX_NUM_ACTIVE_VARIABLES = 37623;
    int GL_NAME_LENGTH = 37625;
    int GL_TYPE = 37626;
    int GL_ARRAY_SIZE = 37627;
    int GL_OFFSET = 37628;
    int GL_BLOCK_INDEX = 37629;
    int GL_ARRAY_STRIDE = 37630;
    int GL_MATRIX_STRIDE = 37631;
    int GL_IS_ROW_MAJOR = 37632;
    int GL_ATOMIC_COUNTER_BUFFER_INDEX = 37633;
    int GL_BUFFER_BINDING = 37634;
    int GL_BUFFER_DATA_SIZE = 37635;
    int GL_NUM_ACTIVE_VARIABLES = 37636;
    int GL_ACTIVE_VARIABLES = 37637;
    int GL_REFERENCED_BY_VERTEX_SHADER = 37638;
    int GL_REFERENCED_BY_FRAGMENT_SHADER = 37642;
    int GL_REFERENCED_BY_COMPUTE_SHADER = 37643;
    int GL_TOP_LEVEL_ARRAY_SIZE = 37644;
    int GL_TOP_LEVEL_ARRAY_STRIDE = 37645;
    int GL_LOCATION = 37646;
    int GL_FRAMEBUFFER_DEFAULT_WIDTH = 37648;
    int GL_FRAMEBUFFER_DEFAULT_HEIGHT = 37649;
    int GL_FRAMEBUFFER_DEFAULT_SAMPLES = 37651;
    int GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS = 37652;
    int GL_MAX_FRAMEBUFFER_WIDTH = 37653;
    int GL_MAX_FRAMEBUFFER_HEIGHT = 37654;
    int GL_MAX_FRAMEBUFFER_SAMPLES = 37656;

    void glDispatchCompute(int num_groups_x, int num_groups_y, int num_groups_z);
    void glDispatchComputeIndirect(long indirect);
    void glDrawArraysIndirect(int mode, long indirect);
    void glDrawElementsIndirect(int mode, int type, long indirect);
    void glFramebufferParameteri(int target, int pname, int param);
    void glGetFramebufferParameteriv(int target, int pname, IntBuffer params);
    void glGetProgramInterfaceiv(int program, int programInterface, int pname, IntBuffer params);
    int glGetProgramResourceIndex(int program, int programInterface, String name);
    String glGetProgramResourceName(int program, int programInterface, int index);
    void glGetProgramResourceiv(int program, int programInterface, int index, IntBuffer props, IntBuffer length, IntBuffer params);
    int glGetProgramResourceLocation(int program, int programInterface, String name);
    void glUseProgramStages(int pipeline, int stages, int program);
    void glActiveShaderProgram(int pipeline, int program);
    int glCreateShaderProgramv(int type, String[] strings);
    void glBindProgramPipeline(int pipeline);
    void glDeleteProgramPipelines(int n, IntBuffer pipelines);
    void glGenProgramPipelines(int n, IntBuffer pipelines);
    boolean glIsProgramPipeline(int pipeline);
    void glGetProgramPipelineiv(int pipeline, int pname, IntBuffer params);
    void glProgramUniform1i(int program, int location, int v0);
    void glProgramUniform2i(int program, int location, int v0, int v1);
    void glProgramUniform3i(int program, int location, int v0, int v1, int v2);
    void glProgramUniform4i(int program, int location, int v0, int v1, int v2, int v3);
    void glProgramUniform1ui(int program, int location, int v0);
    void glProgramUniform2ui(int program, int location, int v0, int v1);
    void glProgramUniform3ui(int program, int location, int v0, int v1, int v2);
    void glProgramUniform4ui(int program, int location, int v0, int v1, int v2, int v3);
    void glProgramUniform1f(int program, int location, float v0);
    void glProgramUniform2f(int program, int location, float v0, float v1);
    void glProgramUniform3f(int program, int location, float v0, float v1, float v2);
    void glProgramUniform4f(int program, int location, float v0, float v1, float v2, float v3);
    void glProgramUniform1iv(int program, int location, IntBuffer value);
    void glProgramUniform2iv(int program, int location, IntBuffer value);
    void glProgramUniform3iv(int program, int location, IntBuffer value);
    void glProgramUniform4iv(int program, int location, IntBuffer value);
    void glProgramUniform1uiv(int program, int location, IntBuffer value);
    void glProgramUniform2uiv(int program, int location, IntBuffer value);
    void glProgramUniform3uiv(int program, int location, IntBuffer value);
    void glProgramUniform4uiv(int program, int location, IntBuffer value);
    void glProgramUniform1fv(int program, int location, FloatBuffer value);
    void glProgramUniform2fv(int program, int location, FloatBuffer value);
    void glProgramUniform3fv(int program, int location, FloatBuffer value);
    void glProgramUniform4fv(int program, int location, FloatBuffer value);
    void glProgramUniformMatrix2fv(int program, int location, boolean transpose, FloatBuffer value);
    void glProgramUniformMatrix3fv(int program, int location, boolean transpose, FloatBuffer value);
    void glProgramUniformMatrix4fv(int program, int location, boolean transpose, FloatBuffer value);
    void glProgramUniformMatrix2x3fv(int program, int location, boolean transpose, FloatBuffer value);
    void glProgramUniformMatrix3x2fv(int program, int location, boolean transpose, FloatBuffer value);
    void glProgramUniformMatrix2x4fv(int program, int location, boolean transpose, FloatBuffer value);
    void glProgramUniformMatrix4x2fv(int program, int location, boolean transpose, FloatBuffer value);
    void glProgramUniformMatrix3x4fv(int program, int location, boolean transpose, FloatBuffer value);
    void glProgramUniformMatrix4x3fv(int program, int location, boolean transpose, FloatBuffer value);
    void glValidateProgramPipeline(int pipeline);
    String glGetProgramPipelineInfoLog(int program);
    void glBindImageTexture(int unit, int texture, int level, boolean layered, int layer, int access, int format);
    void glGetBooleani_v(int target, int index, IntBuffer data);
    void glMemoryBarrier(int barriers);
    void glMemoryBarrierByRegion(int barriers);
    void glTexStorage2DMultisample(int target, int samples, int internalformat, int width, int height, boolean fixedsamplelocations);
    void glGetMultisamplefv(int pname, int index, FloatBuffer val);
    void glSampleMaski(int maskNumber, int mask);
    void glGetTexLevelParameteriv(int target, int level, int pname, IntBuffer params);
    void glGetTexLevelParameterfv(int target, int level, int pname, FloatBuffer params);
    void glBindVertexBuffer(int bindingindex, int buffer, long offset, int stride);
    void glVertexAttribFormat(int attribindex, int size, int type, boolean normalized, int relativeoffset);
    void glVertexAttribIFormat(int attribindex, int size, int type, int relativeoffset);
    void glVertexAttribBinding(int attribindex, int bindingindex);
    void glVertexBindingDivisor(int bindingindex, int divisor);

}