package jpize.gl.texture;

import static org.lwjgl.opengl.GL40.*;

public enum GlTexImg2DTarget {

    TEXTURE_2D                  (GL_TEXTURE_2D                 ), // 3553
    PROXY_TEXTURE_2D            (GL_PROXY_TEXTURE_2D           ), // 32868
    TEXTURE_1D_ARRAY            (GL_TEXTURE_1D_ARRAY           ), // 35864
    PROXY_TEXTURE_1D_ARRAY      (GL_PROXY_TEXTURE_1D_ARRAY     ), // 35865
    TEXTURE_RECTANGLE           (GL_TEXTURE_RECTANGLE          ), // 34037
    PROXY_TEXTURE_RECTANGLE     (GL_PROXY_TEXTURE_RECTANGLE    ), // 34039

    TEXTURE_CUBE_MAP_POSITIVE_X (GL_TEXTURE_CUBE_MAP_POSITIVE_X), // 340_69
    TEXTURE_CUBE_MAP_NEGATIVE_X (GL_TEXTURE_CUBE_MAP_NEGATIVE_X), // 340_70
    TEXTURE_CUBE_MAP_POSITIVE_Y (GL_TEXTURE_CUBE_MAP_POSITIVE_Y), // 340_71
    TEXTURE_CUBE_MAP_NEGATIVE_Y (GL_TEXTURE_CUBE_MAP_NEGATIVE_Y), // 340_72
    TEXTURE_CUBE_MAP_POSITIVE_Z (GL_TEXTURE_CUBE_MAP_POSITIVE_Z), // 340_73
    TEXTURE_CUBE_MAP_NEGATIVE_Z (GL_TEXTURE_CUBE_MAP_NEGATIVE_Z), // 340_74
    PROXY_TEXTURE_CUBE_MAP      (GL_PROXY_TEXTURE_CUBE_MAP     ); // 340_75

    public final int value;

    GlTexImg2DTarget(int value) {
        this.value = value;
    }

}
