/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jpize_stb_freetype_FreeTypeGlyphSlot */

#ifndef _Included_jpize_stb_freetype_FreeTypeGlyphSlot
#define _Included_jpize_stb_freetype_FreeTypeGlyphSlot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jpize_stb_freetype_FreeTypeGlyphSlot
 * Method:    getMetrics
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jpize_stb_freetype_FreeTypeGlyphSlot_getMetrics
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyphSlot
 * Method:    getLinearHoriAdvance
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeGlyphSlot_getLinearHoriAdvance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyphSlot
 * Method:    getLinearVertAdvance
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeGlyphSlot_getLinearVertAdvance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyphSlot
 * Method:    getAdvanceX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeGlyphSlot_getAdvanceX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyphSlot
 * Method:    getAdvanceY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeGlyphSlot_getAdvanceY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyphSlot
 * Method:    getFormat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeGlyphSlot_getFormat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyphSlot
 * Method:    getBitmap
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jpize_stb_freetype_FreeTypeGlyphSlot_getBitmap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyphSlot
 * Method:    getBitmapLeft
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeGlyphSlot_getBitmapLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyphSlot
 * Method:    getBitmapTop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jpize_stb_freetype_FreeTypeGlyphSlot_getBitmapTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyphSlot
 * Method:    renderGlyph
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_jpize_stb_freetype_FreeTypeGlyphSlot_renderGlyph
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jpize_stb_freetype_FreeTypeGlyphSlot
 * Method:    getGlyph
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jpize_stb_freetype_FreeTypeGlyphSlot_getGlyph
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
